# Configurația conexiunii la baza de date
spring.datasource.url=jdbc:postgresql://localhost:5432/taskbuddy_db
spring.datasource.username=taskbuddy_user
spring.datasource.password=password123

# Hibernate/JPA setări
# "update" înseamnă că Spring va crea automat tabelele în baza de date pe baza claselor noastre de Java!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true