# Configurația conexiunii la baza de date
spring.datasource.url=jdbc:postgresql://localhost:5432/taskbuddy_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:schimba_ma_cu_parola_ta_locala}

# Hibernate/JPA setări
# "update" înseamnă că Spring va crea automat tabelele în baza de date pe baza claselor noastre de Java!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true